const DashboardStyles = {
  container: "flex min-h-screen bg-[radial-gradient(circle_at_12%_12%,#e0f2fe_0%,#f8fafc_35%,#f1f5f9_100%)] text-slate-900 overflow-hidden selection:bg-cyan-200 font-sans",
  mobileToggle: "flex md:hidden justify-between items-center bg-white/90 backdrop-blur-md text-slate-800 border-b border-slate-200 shadow-sm px-5 py-3.5 sticky top-0 z-50",
  mobileTitle: "text-xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-slate-800 to-cyan-700",
  toggleButton: "text-slate-500 hover:text-slate-800 transition-colors focus:outline-none p-2 rounded-lg hover:bg-slate-100",
  toggleIcon: "text-2xl",
  sidebar: "bg-white/82 backdrop-blur-xl text-slate-600 w-72 h-screen fixed md:sticky top-0 left-0 py-7 px-5 shadow-sm border-r border-slate-200 flex flex-col justify-between z-40 transition-transform duration-500 ease-[cubic-bezier(0.16,1,0.3,1)]",
  logoContainer: "flex items-center justify-center py-2 mb-8 group transition-transform duration-300",
  logoImage: "w-10 h-10",
  logoText: "text-2xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-slate-900 to-cyan-700 ml-3",
  nav: "space-y-1.5 flex-1",
  navLink: "flex items-center py-3 px-4 rounded-xl transition-all duration-300 group hover:bg-slate-100 border border-transparent",
  navIcon: "mr-3 text-slate-400 group-hover:text-cyan-700 transition-colors duration-300",
  navText: "text-sm font-semibold tracking-wide group-hover:translate-x-0.5 transition-transform duration-300",
  activeLink: "bg-cyan-50 border border-cyan-200 text-cyan-800 shadow-sm",
  sidebarFooter: "self-end flex flex-col items-center py-5 border-t border-slate-200 w-full mt-auto",
  credits: "text-xs font-bold tracking-wide uppercase text-slate-400 mb-3",
  avatarContainer: "cursor-pointer group relative",
  avatarImage: "w-12 h-12 rounded-full border-2 border-cyan-200 p-0.5 mb-2 group-hover:scale-105 transition-all duration-300 bg-white",
  userInfo: "text-center transition-all duration-300",
  userName: "text-sm font-bold text-slate-800",
  userEmail: "text-xs text-slate-500 font-medium",
  userCard: "absolute right-[-10px] md:right-auto md:left-full md:ml-4 bottom-0 md:bottom-auto mb-20 md:mb-0 bg-white border border-slate-200 rounded-2xl shadow-lg p-5 z-50 animate-slide-up-fade min-w-[220px]",
  cardHeader: "flex items-center mb-1",
  cardAvatar: "w-10 h-10 rounded-full border-2 border-cyan-200 mr-3",
  cardUserName: "font-bold text-slate-900 text-sm",
  cardUserEmail: "text-xs text-slate-500",
  mainContent: "flex-1 w-full max-w-7xl mx-auto p-4 md:p-8 lg:p-10 relative z-10",
};

export default DashboardStyles;
