const DashboardStyles = {
  container: "flex min-h-screen bg-brand-dark text-brand-textDark overflow-hidden selection:bg-accent-purple font-sans",
  mobileToggle: "flex md:hidden justify-between items-center bg-white/80 backdrop-blur-md text-brand-textDark border-b border-brand-light shadow-glass-sm px-6 py-4 sticky top-0 z-50",
  mobileTitle: "text-2xl font-black tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-accent-purple to-accent-pink",
  toggleButton: "text-brand-textLight hover:text-brand-textDark transition-colors focus:outline-none p-2 rounded-lg hover:bg-black/5",
  toggleIcon: "text-2xl",
  sidebar: "bg-white/70 backdrop-blur-2xl text-brand-textLight w-72 h-screen fixed md:sticky top-0 left-0 py-8 px-6 shadow-glass-lg border-r border-brand-light flex flex-col justify-between z-40 transition-transform duration-500 ease-[cubic-bezier(0.16,1,0.3,1)]",
  logoContainer: "flex items-center justify-center py-2 mb-10 group hover:scale-105 transition-transform duration-300",
  logoImage: "w-12 h-12 drop-shadow-[0_0_15px_rgba(139,92,246,0.3)]",
  logoText: "text-3xl font-black tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-brand-textDark to-brand-textLight ml-4",
  nav: "space-y-2 flex-1",
  navLink: "flex items-center py-4 px-5 rounded-2xl transition-all duration-300 group hover:bg-black/5 border border-transparent hover:border-brand-light",
  navIcon: "mr-4 text-brand-textLight group-hover:text-accent-purple transition-colors duration-300",
  navText: "text-sm font-bold tracking-wide group-hover:translate-x-1 transition-transform duration-300",
  activeLink: "bg-gradient-to-r from-accent-purple/10 to-accent-pink/5 border border-accent-purple/20 text-accent-purple shadow-sm",
  sidebarFooter: "self-end flex flex-col items-center py-6 border-t border-brand-light w-full mt-auto",
  credits: "text-xs font-bold tracking-widest uppercase text-gray-400 mb-4",
  avatarContainer: "cursor-pointer group relative",
  avatarImage: "w-14 h-14 rounded-full border-2 border-accent-purple/30 p-0.5 mb-2 group-hover:scale-110 group-hover:shadow-glow-purple transition-all duration-300 bg-white",
  userInfo: "text-center transition-all duration-300",
  userName: "text-sm font-extrabold text-brand-textDark group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-accent-purple group-hover:to-accent-pink",
  userEmail: "text-xs text-brand-textLight font-semibold",
  userCard: "absolute right-[-10px] md:right-auto md:left-full md:ml-4 bottom-0 md:bottom-auto mb-20 md:mb-0 bg-white/90 border border-brand-light rounded-2xl shadow-glass-lg p-5 z-50 animate-slide-up-fade min-w-[200px] backdrop-blur-xl",
  cardHeader: "flex items-center mb-1",
  cardAvatar: "w-10 h-10 rounded-full border-2 border-accent-purple/30 mr-3",
  cardUserName: "font-extrabold text-brand-textDark text-sm",
  cardUserEmail: "text-xs text-brand-textLight",
  mainContent: "flex-1 w-full max-w-7xl mx-auto p-6 md:p-10 lg:p-14 relative z-10",
};

export default DashboardStyles;
